apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: console-toolkit
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: console-toolkit
      annotations:
        iam.amazonaws.com/role: datalake-dev-stg
    spec:
      containers:
      - name: console-toolkit
        imagePullPolicy: Always
        image: wuwenmin1991/console-toolkit:latest
        resources:
          limits:
            cpu: 4000m
            memory: 32Gi
          requests:
            cpu: 2000m
            memory: 8Gi
        volumeMounts:
          - name: console-volume
            mountPath: /home/jovyan/work
            readOnly: false
        workingDir: /home/jovyan/work
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: [
            "--NotebookApp.password='sha1:268a0bccbec0:572e98fc05d4d359317cc92c04ff4f6c43b21843'",
            "--ContentsManager.allow_hidden=True"
            ]
        env:
          - name: SHELL
            value: "zsh"
      volumes:
        - name: console-volume
          persistentVolumeClaim:
            claimName: toolkit-volume
